#Analisando os dados dos alunos ingressantes na UFMA

In [14]:
import pandas as pd
url_2018 = 'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/94c390a1-af05-49df-a42c-de11f1187999/download/alunos_ingressantes_-_2018.1.csv'

df = pd.read_csv(url_2018, sep=';')
#df.head() : -> método utilizado para uma menor visualização do df (com apenas 5 colunas)
#df.info(): -> utilizei esse método para verificar se os dados foram carregados corretamente
df.columns # método que mostra o nome das colunas e ficar mais fácil para selecioná-las

colunas = ['municipio', 'curso','grau','turno','modalidade', 'nivel','forma_ingresso','ano','periodo','quantidade']
df = pd.read_csv(url_2018, sep = ';', usecols= colunas)
df.head()

,municipio,curso,grau,turno,modalidade,nivel,forma_ingresso,ano,periodo,quantidade
0,BACABAL,LETRAS - PORTUGUÊS,LICENCIATURA,Vespertino,Presencial,G,SISU - AMPLA CONCORRÊNCIA,2018,1,24
1,BACABAL,LETRAS - PORTUGUÊS,LICENCIATURA,Vespertino,Presencial,G,SISU - ESCOLA PÚBLICA,2018,1,2
2,BACABAL,LETRAS - PORTUGUÊS,LICENCIATURA,Vespertino,Presencial,G,SISU - ESCOLA PUBLICA - DEFICIENTE - RF,2018,1,1
3,BACABAL,LETRAS - PORTUGUÊS,LICENCIATURA,Vespertino,Presencial,G,SISU - ESCOLA PUBLICA - NEGRO,2018,1,10
4,BACABAL,LETRAS - PORTUGUÊS,LICENCIATURA,Vespertino,Presencial,G,SISU - ESCOLA PUBLICA - NEGRO - DEFICIENTE - RF,2018,1,1

In [15]:
#Ordenando os cursos agora pela quantidade de ingressantes

df.sort_values('quantidade')
df.groupby('curso')['quantidade'].sum().sort_values(ascending = False).head(10)

curso
CIÊNCIA E TECNOLOGIA               195
DIREITO                            123
MEDICINA                           109
PEDAGOGIA                          105
ENFERMAGEM                          92
CIÊNCIAS BIOLÓGICAS                 77
EDUCAÇÃO FÍSICA                     76
COMUNICAÇÃO SOCIAL - JORNALISMO     60
LETRAS - PORTUGUÊS                  47
ADMINISTRAÇÃO                       45
Name: quantidade, dtype: int64

In [16]:
df.groupby(['curso','municipio','turno'])['quantidade'].sum().sort_values(ascending = False).head(10)

curso                            municipio   turno
CIÊNCIA E TECNOLOGIA             SÃO LUÍS    Matutino                 98
                                             Noturno                  97
MEDICINA                         SÃO LUÍS    Matutino e Vespertino    53
ENFERMAGEM                       IMPERATRIZ  Matutino e Vespertino    48
LETRAS - PORTUGUÊS               BACABAL     Vespertino               47
COMUNICAÇÃO SOCIAL - JORNALISMO  IMPERATRIZ  Vespertino               46
ADMINISTRAÇÃO                    SÃO LUÍS    Matutino                 45
DIREITO                          SÃO LUÍS    Matutino                 44
MATEMÁTICA                       SÃO LUÍS    Vespertino               44
CIÊNCIAS ECONÔMICAS              SÃO LUÍS    Vespertino               44
Name: quantidade, dtype: int64

In [40]:
urls = [
    'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/94c390a1-af05-49df-a42c-de11f1187999/download/alunos_ingressantes_-_2018.1.csv',
    'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/876d6fe4-a5c1-4252-860e-e878733ae85c/download/alunos_ingressantes_-_2018.2.csv',
    'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/75843aa8-951b-464b-8d0e-39fdf62fa79f/download/alunos_ingressantes_-_2019.1.csv',
    'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/42226a8b-5ec4-4886-b372-85cbb56d0496/download/alunos_ingressantes_-_2019.2.csv',
    'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/573a5221-5228-44ee-8857-f4cc33b1ee6a/download/alunos_ingressantes_-_2020.1.csv',
    'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/77ccde1b-7bfe-4342-bcf1-7a5075982d96/download/alunos_ingressantes_-_2020.2.csv',
    'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/61fff8f0-4c95-4293-9921-d3a92d09af26/download/alunos_ingressantes_-_2021-1.csv',
    'http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/b473e197-50e5-4c2d-91ff-8bc2291cd9f3/download/alunos_ingressantes_-_2021.2.csv'
]
colunas = ['municipio', 'curso','grau','turno','modalidade', 'nivel','forma_ingresso','ano','periodo','quantidade']
def load_dataframe_by_urls(urls, colunas):
  df_total =pd.DataFrame() #um dataframe vazio
  for url in urls:
    print("URL", url)
    df = pd.read_csv(url, sep = ';', usecols=colunas)
    df_total = pd.concat([df_total, df])
  return df_total

In [42]:
df_ingressantes = load_dataframe_by_urls(urls,colunas)
df_ingressantes.info()

URL http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/94c390a1-af05-49df-a42c-de11f1187999/download/alunos_ingressantes_-_2018.1.csv
URL http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/876d6fe4-a5c1-4252-860e-e878733ae85c/download/alunos_ingressantes_-_2018.2.csv
URL http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/75843aa8-951b-464b-8d0e-39fdf62fa79f/download/alunos_ingressantes_-_2019.1.csv
URL http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/42226a8b-5ec4-4886-b372-85cbb56d0496/download/alunos_ingressantes_-_2019.2.csv
URL http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/573a5221-5228-44ee-8857-f4cc33b1ee6a/download/alunos_ingressantes_-_2020.1.csv
URL http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/77ccde1b-7bfe-4342-bcf1-7a5075982d96/download/alunos_ingressantes_-_2020.2.csv
URL http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/61fff8f0-4c95-4293-9921-d3a92d09af26/download/alunos_ingressantes_-_2021-1.csv
URL http://dadosabertos.ufma.br/dataset/36d814e1-baa0-466c-86d8-73714c076755/resource/b473e197-50e5-4c2d-91ff-8bc2291cd9f3/download/alunos_ingressantes_-_2021.2.csv
<class 'pandas.core.frame.DataFrame'>
Index: 3421 entries, 0 to 427
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   municipio       3421 non-null   object
 1   curso           3421 non-null   object
 2   grau            3421 non-null   object
 3   turno           3421 non-null   object
 4   modalidade      3421 non-null   object
 5   nivel           3421 non-null   object
 6   forma_ingresso  3421 non-null   object
 7   ano             3420 non-null   float64
 8   periodo         3420 non-null   float64
 9   quantidade      3420 non-null   float64
dtypes: float64(3), object(7)
memory usage: 294.0+ KB

In [49]:
df_ingressantes['ano'].isna().sum()
df_ingressantes.dropna(inplace=True)

In [50]:
df_ingressantes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3420 entries, 0 to 427
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   municipio       3420 non-null   object
 1   curso           3420 non-null   object
 2   grau            3420 non-null   object
 3   turno           3420 non-null   object
 4   modalidade      3420 non-null   object
 5   nivel           3420 non-null   object
 6   forma_ingresso  3420 non-null   object
 7   ano             3420 non-null   float64
 8   periodo         3420 non-null   float64
 9   quantidade      3420 non-null   float64
dtypes: float64(3), object(7)
memory usage: 293.9+ KB

In [51]:
df_ingressantes = df_ingressantes.astype(
    {'ano':'int32','periodo':'int32','quantidade':'int32'}
)
df_ingressantes.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3420 entries, 0 to 427
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   municipio       3420 non-null   object
 1   curso           3420 non-null   object
 2   grau            3420 non-null   object
 3   turno           3420 non-null   object
 4   modalidade      3420 non-null   object
 5   nivel           3420 non-null   object
 6   forma_ingresso  3420 non-null   object
 7   ano             3420 non-null   int32
 8   periodo         3420 non-null   int32
 9   quantidade      3420 non-null   int32
dtypes: int32(3), object(7)
memory usage: 253.8+ KB

In [52]:
df_ingressantes['nome_completo'] = df_ingressantes['curso'] + '-' + df_ingressantes['municipio'] + '-' + df_ingressantes['turno']
df_ingressantes['nome_completo']

0      LETRAS - PORTUGUÊS-BACABAL-Vespertino
1      LETRAS - PORTUGUÊS-BACABAL-Vespertino
2      LETRAS - PORTUGUÊS-BACABAL-Vespertino
3      LETRAS - PORTUGUÊS-BACABAL-Vespertino
4      LETRAS - PORTUGUÊS-BACABAL-Vespertino
                       ...
423                TURISMO-SÃO LUÍS-Matutino
424                TURISMO-SÃO LUÍS-Matutino
425                TURISMO-SÃO LUÍS-Matutino
426                TURISMO-SÃO LUÍS-Matutino
427                TURISMO-SÃO LUÍS-Matutino
Name: nome_completo, Length: 3420, dtype: object

In [55]:
df_presencial = df_ingressantes.query("modalidade == 'Presencial'")
df_presencial.groupby('nome_completo')['quantidade'].mean().head(10)

nome_completo
ADMINISTRAÇÃO-SÃO LUÍS-Matutino                         6.535714
AGRONOMIA-CHAPADINHA-Matutino e Vespertino              6.578947
ARTES VISUAIS-SÃO LUÍS-Matutino                         4.512821
BIBLIOTECONOMIA-SÃO LUÍS-Matutino                       6.568627
CIÊNCIA DA COMPUTAÇÃO-SÃO LUÍS-Vespertino               6.760000
CIÊNCIA DA COMPUTAÇÃO-SÃO LUÍS-Vespertino e Noturno     6.407407
CIÊNCIA E TECNOLOGIA-BALSAS-Matutino                    6.714286
CIÊNCIA E TECNOLOGIA-BALSAS-Noturno                     7.047619
CIÊNCIA E TECNOLOGIA-SÃO LUÍS-Matutino                 15.271186
CIÊNCIA E TECNOLOGIA-SÃO LUÍS-Noturno                  13.075758
Name: quantidade, dtype: float64

In [56]:
grupo = ['nome_completo','ano','periodo']
df_por_semestre = df_presencial.groupby(grupo)['quantidade'].sum()
df_por_semestre.head(10)

nome_completo                               ano   periodo
ADMINISTRAÇÃO-SÃO LUÍS-Matutino             2018  1          45
                                                  2          55
                                            2019  1          47
                                                  2          46
                                            2020  1          36
                                                  2          41
                                            2021  1          49
                                                  2          47
AGRONOMIA-CHAPADINHA-Matutino e Vespertino  2018  1          38
                                                  2          33
Name: quantidade, dtype: int32

In [57]:
media_por_curso = df_por_semestre.groupby('nome_completo').mean()
media_por_curso.sort_values(ascending=False).head(10)

nome_completo
CIÊNCIA E TECNOLOGIA-SÃO LUÍS-Matutino                      112.625
CIÊNCIA E TECNOLOGIA-SÃO LUÍS-Noturno                       107.875
PEDAGOGIA-GRAJAÚ-Matutino e Vespertino                       84.000
PEDAGOGIA-LAGO DA PEDRA-Matutino e Vespertino                70.000
HISTÓRIA-LAGO DO JUNCO-Matutino e Vespertino                 60.000
PEDAGOGIA-LAGOA GRANDE DO MARANHÃO-Matutino e Vespertino     59.000
PEDAGOGIA-BURITI BRAVO-Matutino e Vespertino                 59.000
PEDAGOGIA-URBANO SANTOS-Matutino e Vespertino                58.000
CIÊNCIAS NATURAIS - BIOLOGIA-PINHEIRO-Noturno                57.750
CIÊNCIAS HUMANAS - SOCIOLOGIA-SÃO BERNARDO-Noturno           57.500
Name: quantidade, dtype: float64